# Generated by Django 2.0.3 on 2018-07-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34, verbose_name='Имя')),
                ('telephone', models.CharField(max_length=34, verbose_name='Телефон')),
                ('email', models.CharField(max_length=34, verbose_name='Почта')),
            ],
        ),
    ]
